// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_msg.proto

package com.owl.card.common.protobuf.cs;

/**
 * Protobuf type {@code CardGroupDel}
 *
 * <pre>
 * msgType = 24
 * 客户端 -&gt; 服务器
 * 删除卡组
 * </pre>
 */
public  final class CardGroupDel extends
    com.google.protobuf.GeneratedMessage
    implements CardGroupDelOrBuilder {
  // Use CardGroupDel.newBuilder() to construct.
  private CardGroupDel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private CardGroupDel(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final CardGroupDel defaultInstance;
  public static CardGroupDel getDefaultInstance() {
    return defaultInstance;
  }

  public CardGroupDel getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private CardGroupDel(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            groupId_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_CardGroupDel_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_CardGroupDel_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.owl.card.common.protobuf.cs.CardGroupDel.class, com.owl.card.common.protobuf.cs.CardGroupDel.Builder.class);
  }

  public static com.google.protobuf.Parser<CardGroupDel> PARSER =
      new com.google.protobuf.AbstractParser<CardGroupDel>() {
    public CardGroupDel parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CardGroupDel(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<CardGroupDel> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required int64 groupId = 1;
  public static final int GROUPID_FIELD_NUMBER = 1;
  private long groupId_;
  /**
   * <code>required int64 groupId = 1;</code>
   *
   * <pre>
   * 卡组编号
   * </pre>
   */
  public boolean hasGroupId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int64 groupId = 1;</code>
   *
   * <pre>
   * 卡组编号
   * </pre>
   */
  public long getGroupId() {
    return groupId_;
  }

  private void initFields() {
    groupId_ = 0L;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasGroupId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt64(1, groupId_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, groupId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.owl.card.common.protobuf.cs.CardGroupDel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupDel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupDel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupDel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupDel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupDel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupDel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupDel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupDel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupDel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.owl.card.common.protobuf.cs.CardGroupDel prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CardGroupDel}
   *
   * <pre>
   * msgType = 24
   * 客户端 -&gt; 服务器
   * 删除卡组
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.owl.card.common.protobuf.cs.CardGroupDelOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_CardGroupDel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_CardGroupDel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.owl.card.common.protobuf.cs.CardGroupDel.class, com.owl.card.common.protobuf.cs.CardGroupDel.Builder.class);
    }

    // Construct using com.owl.card.common.protobuf.cs.CardGroupDel.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      groupId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_CardGroupDel_descriptor;
    }

    public com.owl.card.common.protobuf.cs.CardGroupDel getDefaultInstanceForType() {
      return com.owl.card.common.protobuf.cs.CardGroupDel.getDefaultInstance();
    }

    public com.owl.card.common.protobuf.cs.CardGroupDel build() {
      com.owl.card.common.protobuf.cs.CardGroupDel result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.owl.card.common.protobuf.cs.CardGroupDel buildPartial() {
      com.owl.card.common.protobuf.cs.CardGroupDel result = new com.owl.card.common.protobuf.cs.CardGroupDel(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.groupId_ = groupId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.owl.card.common.protobuf.cs.CardGroupDel) {
        return mergeFrom((com.owl.card.common.protobuf.cs.CardGroupDel)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.owl.card.common.protobuf.cs.CardGroupDel other) {
      if (other == com.owl.card.common.protobuf.cs.CardGroupDel.getDefaultInstance()) return this;
      if (other.hasGroupId()) {
        setGroupId(other.getGroupId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasGroupId()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.owl.card.common.protobuf.cs.CardGroupDel parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.owl.card.common.protobuf.cs.CardGroupDel) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required int64 groupId = 1;
    private long groupId_ ;
    /**
     * <code>required int64 groupId = 1;</code>
     *
     * <pre>
     * 卡组编号
     * </pre>
     */
    public boolean hasGroupId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 groupId = 1;</code>
     *
     * <pre>
     * 卡组编号
     * </pre>
     */
    public long getGroupId() {
      return groupId_;
    }
    /**
     * <code>required int64 groupId = 1;</code>
     *
     * <pre>
     * 卡组编号
     * </pre>
     */
    public Builder setGroupId(long value) {
      bitField0_ |= 0x00000001;
      groupId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 groupId = 1;</code>
     *
     * <pre>
     * 卡组编号
     * </pre>
     */
    public Builder clearGroupId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      groupId_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:CardGroupDel)
  }

  static {
    defaultInstance = new CardGroupDel(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:CardGroupDel)
}

