// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_msg.proto

package com.owl.card.common.protobuf.cs;

public final class CardGamePkt {
  private CardGamePkt() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserLoginC2S_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserLoginC2S_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserLoginS2C_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserLoginS2C_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016game_msg.proto\032\020msg_struct.proto\"=\n\014Us" +
      "erLoginC2S\022\r\n\005accid\030\001 \002(\005\022\016\n\006tstamp\030\002 \002(" +
      "\005\022\016\n\006ticket\030\003 \002(\t\";\n\014UserLoginS2C\022\n\n\002rt\030" +
      "\001 \002(\005\022\037\n\010roleInfo\030\002 \001(\0132\r.RoleInfoDataB0" +
      "\n\037com.owl.card.common.protobuf.csB\013CardG" +
      "amePktP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.owl.card.common.protobuf.struct.CardStructPkt.getDescriptor(),
        }, assigner);
    internal_static_UserLoginC2S_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserLoginC2S_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserLoginC2S_descriptor,
        new java.lang.String[] { "Accid", "Tstamp", "Ticket", });
    internal_static_UserLoginS2C_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserLoginS2C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserLoginS2C_descriptor,
        new java.lang.String[] { "Rt", "RoleInfo", });
    com.owl.card.common.protobuf.struct.CardStructPkt.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
