// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_msg.proto

package com.owl.card.common.protobuf.cs;

public interface CardGroupDelRtOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required int32 rt = 1;
  /**
   * <code>required int32 rt = 1;</code>
   */
  boolean hasRt();
  /**
   * <code>required int32 rt = 1;</code>
   */
  int getRt();

  // required int64 groupId = 2;
  /**
   * <code>required int64 groupId = 2;</code>
   *
   * <pre>
   * 卡组编号	
   * </pre>
   */
  boolean hasGroupId();
  /**
   * <code>required int64 groupId = 2;</code>
   *
   * <pre>
   * 卡组编号	
   * </pre>
   */
  long getGroupId();
}
