// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_msg.proto

package com.owl.card.common.protobuf.cs;

/**
 * Protobuf type {@code CardGroupAdd}
 *
 * <pre>
 * msgType = 20
 * 客户端 -&gt; 服务器
 * 添加卡组
 * </pre>
 */
public  final class CardGroupAdd extends
    com.google.protobuf.GeneratedMessage
    implements CardGroupAddOrBuilder {
  // Use CardGroupAdd.newBuilder() to construct.
  private CardGroupAdd(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private CardGroupAdd(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final CardGroupAdd defaultInstance;
  public static CardGroupAdd getDefaultInstance() {
    return defaultInstance;
  }

  public CardGroupAdd getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private CardGroupAdd(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            hero_ = input.readInt32();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            groupName_ = input.readBytes();
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              cardProtoId_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000004;
            }
            cardProtoId_.add(input.readInt32());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
              cardProtoId_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              cardProtoId_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        cardProtoId_ = java.util.Collections.unmodifiableList(cardProtoId_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_CardGroupAdd_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_CardGroupAdd_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.owl.card.common.protobuf.cs.CardGroupAdd.class, com.owl.card.common.protobuf.cs.CardGroupAdd.Builder.class);
  }

  public static com.google.protobuf.Parser<CardGroupAdd> PARSER =
      new com.google.protobuf.AbstractParser<CardGroupAdd>() {
    public CardGroupAdd parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CardGroupAdd(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<CardGroupAdd> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required int32 hero = 1;
  public static final int HERO_FIELD_NUMBER = 1;
  private int hero_;
  /**
   * <code>required int32 hero = 1;</code>
   *
   * <pre>
   * 英雄
   * </pre>
   */
  public boolean hasHero() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int32 hero = 1;</code>
   *
   * <pre>
   * 英雄
   * </pre>
   */
  public int getHero() {
    return hero_;
  }

  // required string groupName = 2;
  public static final int GROUPNAME_FIELD_NUMBER = 2;
  private java.lang.Object groupName_;
  /**
   * <code>required string groupName = 2;</code>
   *
   * <pre>
   * 卡组名称
   * </pre>
   */
  public boolean hasGroupName() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required string groupName = 2;</code>
   *
   * <pre>
   * 卡组名称
   * </pre>
   */
  public java.lang.String getGroupName() {
    java.lang.Object ref = groupName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        groupName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string groupName = 2;</code>
   *
   * <pre>
   * 卡组名称
   * </pre>
   */
  public com.google.protobuf.ByteString
      getGroupNameBytes() {
    java.lang.Object ref = groupName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groupName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // repeated int32 cardProtoId = 3;
  public static final int CARDPROTOID_FIELD_NUMBER = 3;
  private java.util.List<java.lang.Integer> cardProtoId_;
  /**
   * <code>repeated int32 cardProtoId = 3;</code>
   *
   * <pre>
   * 卡牌编号
   * </pre>
   */
  public java.util.List<java.lang.Integer>
      getCardProtoIdList() {
    return cardProtoId_;
  }
  /**
   * <code>repeated int32 cardProtoId = 3;</code>
   *
   * <pre>
   * 卡牌编号
   * </pre>
   */
  public int getCardProtoIdCount() {
    return cardProtoId_.size();
  }
  /**
   * <code>repeated int32 cardProtoId = 3;</code>
   *
   * <pre>
   * 卡牌编号
   * </pre>
   */
  public int getCardProtoId(int index) {
    return cardProtoId_.get(index);
  }

  private void initFields() {
    hero_ = 0;
    groupName_ = "";
    cardProtoId_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasHero()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasGroupName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, hero_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getGroupNameBytes());
    }
    for (int i = 0; i < cardProtoId_.size(); i++) {
      output.writeInt32(3, cardProtoId_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, hero_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getGroupNameBytes());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < cardProtoId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(cardProtoId_.get(i));
      }
      size += dataSize;
      size += 1 * getCardProtoIdList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.owl.card.common.protobuf.cs.CardGroupAdd parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupAdd parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupAdd parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupAdd parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupAdd parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupAdd parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupAdd parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupAdd parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupAdd parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.owl.card.common.protobuf.cs.CardGroupAdd parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.owl.card.common.protobuf.cs.CardGroupAdd prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CardGroupAdd}
   *
   * <pre>
   * msgType = 20
   * 客户端 -&gt; 服务器
   * 添加卡组
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.owl.card.common.protobuf.cs.CardGroupAddOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_CardGroupAdd_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_CardGroupAdd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.owl.card.common.protobuf.cs.CardGroupAdd.class, com.owl.card.common.protobuf.cs.CardGroupAdd.Builder.class);
    }

    // Construct using com.owl.card.common.protobuf.cs.CardGroupAdd.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      hero_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      groupName_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      cardProtoId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_CardGroupAdd_descriptor;
    }

    public com.owl.card.common.protobuf.cs.CardGroupAdd getDefaultInstanceForType() {
      return com.owl.card.common.protobuf.cs.CardGroupAdd.getDefaultInstance();
    }

    public com.owl.card.common.protobuf.cs.CardGroupAdd build() {
      com.owl.card.common.protobuf.cs.CardGroupAdd result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.owl.card.common.protobuf.cs.CardGroupAdd buildPartial() {
      com.owl.card.common.protobuf.cs.CardGroupAdd result = new com.owl.card.common.protobuf.cs.CardGroupAdd(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.hero_ = hero_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.groupName_ = groupName_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        cardProtoId_ = java.util.Collections.unmodifiableList(cardProtoId_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.cardProtoId_ = cardProtoId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.owl.card.common.protobuf.cs.CardGroupAdd) {
        return mergeFrom((com.owl.card.common.protobuf.cs.CardGroupAdd)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.owl.card.common.protobuf.cs.CardGroupAdd other) {
      if (other == com.owl.card.common.protobuf.cs.CardGroupAdd.getDefaultInstance()) return this;
      if (other.hasHero()) {
        setHero(other.getHero());
      }
      if (other.hasGroupName()) {
        bitField0_ |= 0x00000002;
        groupName_ = other.groupName_;
        onChanged();
      }
      if (!other.cardProtoId_.isEmpty()) {
        if (cardProtoId_.isEmpty()) {
          cardProtoId_ = other.cardProtoId_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureCardProtoIdIsMutable();
          cardProtoId_.addAll(other.cardProtoId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasHero()) {
        
        return false;
      }
      if (!hasGroupName()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.owl.card.common.protobuf.cs.CardGroupAdd parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.owl.card.common.protobuf.cs.CardGroupAdd) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required int32 hero = 1;
    private int hero_ ;
    /**
     * <code>required int32 hero = 1;</code>
     *
     * <pre>
     * 英雄
     * </pre>
     */
    public boolean hasHero() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 hero = 1;</code>
     *
     * <pre>
     * 英雄
     * </pre>
     */
    public int getHero() {
      return hero_;
    }
    /**
     * <code>required int32 hero = 1;</code>
     *
     * <pre>
     * 英雄
     * </pre>
     */
    public Builder setHero(int value) {
      bitField0_ |= 0x00000001;
      hero_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 hero = 1;</code>
     *
     * <pre>
     * 英雄
     * </pre>
     */
    public Builder clearHero() {
      bitField0_ = (bitField0_ & ~0x00000001);
      hero_ = 0;
      onChanged();
      return this;
    }

    // required string groupName = 2;
    private java.lang.Object groupName_ = "";
    /**
     * <code>required string groupName = 2;</code>
     *
     * <pre>
     * 卡组名称
     * </pre>
     */
    public boolean hasGroupName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string groupName = 2;</code>
     *
     * <pre>
     * 卡组名称
     * </pre>
     */
    public java.lang.String getGroupName() {
      java.lang.Object ref = groupName_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        groupName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string groupName = 2;</code>
     *
     * <pre>
     * 卡组名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getGroupNameBytes() {
      java.lang.Object ref = groupName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string groupName = 2;</code>
     *
     * <pre>
     * 卡组名称
     * </pre>
     */
    public Builder setGroupName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      groupName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string groupName = 2;</code>
     *
     * <pre>
     * 卡组名称
     * </pre>
     */
    public Builder clearGroupName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      groupName_ = getDefaultInstance().getGroupName();
      onChanged();
      return this;
    }
    /**
     * <code>required string groupName = 2;</code>
     *
     * <pre>
     * 卡组名称
     * </pre>
     */
    public Builder setGroupNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      groupName_ = value;
      onChanged();
      return this;
    }

    // repeated int32 cardProtoId = 3;
    private java.util.List<java.lang.Integer> cardProtoId_ = java.util.Collections.emptyList();
    private void ensureCardProtoIdIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        cardProtoId_ = new java.util.ArrayList<java.lang.Integer>(cardProtoId_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated int32 cardProtoId = 3;</code>
     *
     * <pre>
     * 卡牌编号
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getCardProtoIdList() {
      return java.util.Collections.unmodifiableList(cardProtoId_);
    }
    /**
     * <code>repeated int32 cardProtoId = 3;</code>
     *
     * <pre>
     * 卡牌编号
     * </pre>
     */
    public int getCardProtoIdCount() {
      return cardProtoId_.size();
    }
    /**
     * <code>repeated int32 cardProtoId = 3;</code>
     *
     * <pre>
     * 卡牌编号
     * </pre>
     */
    public int getCardProtoId(int index) {
      return cardProtoId_.get(index);
    }
    /**
     * <code>repeated int32 cardProtoId = 3;</code>
     *
     * <pre>
     * 卡牌编号
     * </pre>
     */
    public Builder setCardProtoId(
        int index, int value) {
      ensureCardProtoIdIsMutable();
      cardProtoId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 cardProtoId = 3;</code>
     *
     * <pre>
     * 卡牌编号
     * </pre>
     */
    public Builder addCardProtoId(int value) {
      ensureCardProtoIdIsMutable();
      cardProtoId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 cardProtoId = 3;</code>
     *
     * <pre>
     * 卡牌编号
     * </pre>
     */
    public Builder addAllCardProtoId(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureCardProtoIdIsMutable();
      super.addAll(values, cardProtoId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 cardProtoId = 3;</code>
     *
     * <pre>
     * 卡牌编号
     * </pre>
     */
    public Builder clearCardProtoId() {
      cardProtoId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:CardGroupAdd)
  }

  static {
    defaultInstance = new CardGroupAdd(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:CardGroupAdd)
}

