// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_msg.proto

package com.owl.card.common.protobuf.cs;

public interface CardGroupDelOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required int64 groupId = 1;
  /**
   * <code>required int64 groupId = 1;</code>
   *
   * <pre>
   * 卡组编号
   * </pre>
   */
  boolean hasGroupId();
  /**
   * <code>required int64 groupId = 1;</code>
   *
   * <pre>
   * 卡组编号
   * </pre>
   */
  long getGroupId();
}
