// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_msg.proto

package com.owl.card.common.protobuf.cs;

public interface CardGroupAddOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required int32 hero = 1;
  /**
   * <code>required int32 hero = 1;</code>
   *
   * <pre>
   * 英雄
   * </pre>
   */
  boolean hasHero();
  /**
   * <code>required int32 hero = 1;</code>
   *
   * <pre>
   * 英雄
   * </pre>
   */
  int getHero();

  // required string groupName = 2;
  /**
   * <code>required string groupName = 2;</code>
   *
   * <pre>
   * 卡组名称
   * </pre>
   */
  boolean hasGroupName();
  /**
   * <code>required string groupName = 2;</code>
   *
   * <pre>
   * 卡组名称
   * </pre>
   */
  java.lang.String getGroupName();
  /**
   * <code>required string groupName = 2;</code>
   *
   * <pre>
   * 卡组名称
   * </pre>
   */
  com.google.protobuf.ByteString
      getGroupNameBytes();

  // repeated int32 cardProtoId = 3;
  /**
   * <code>repeated int32 cardProtoId = 3;</code>
   *
   * <pre>
   * 卡牌编号
   * </pre>
   */
  java.util.List<java.lang.Integer> getCardProtoIdList();
  /**
   * <code>repeated int32 cardProtoId = 3;</code>
   *
   * <pre>
   * 卡牌编号
   * </pre>
   */
  int getCardProtoIdCount();
  /**
   * <code>repeated int32 cardProtoId = 3;</code>
   *
   * <pre>
   * 卡牌编号
   * </pre>
   */
  int getCardProtoId(int index);
}
