// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_msg.proto

package com.owl.card.common.protobuf.cs;

/**
 * Protobuf type {@code UserLoginS2C}
 *
 * <pre>
 * msgType = 11
 * 服务器 -&gt; 客户端
 * 客户端请求登陆返回
 * </pre>
 */
public final class UserLoginS2C extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:UserLoginS2C)
    UserLoginS2COrBuilder {
  // Use UserLoginS2C.newBuilder() to construct.
  private UserLoginS2C(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private UserLoginS2C(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final UserLoginS2C defaultInstance;
  public static UserLoginS2C getDefaultInstance() {
    return defaultInstance;
  }

  public UserLoginS2C getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private UserLoginS2C(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            flag_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_UserLoginS2C_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_UserLoginS2C_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.owl.card.common.protobuf.cs.UserLoginS2C.class, com.owl.card.common.protobuf.cs.UserLoginS2C.Builder.class);
  }

  public static com.google.protobuf.Parser<UserLoginS2C> PARSER =
      new com.google.protobuf.AbstractParser<UserLoginS2C>() {
    public UserLoginS2C parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserLoginS2C(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<UserLoginS2C> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int FLAG_FIELD_NUMBER = 1;
  private int flag_;
  /**
   * <code>required int32 flag = 1;</code>
   *
   * <pre>
   *0:验证错误 1:登录成功
   * </pre>
   */
  public boolean hasFlag() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int32 flag = 1;</code>
   *
   * <pre>
   *0:验证错误 1:登录成功
   * </pre>
   */
  public int getFlag() {
    return flag_;
  }

  private void initFields() {
    flag_ = 0;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasFlag()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, flag_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, flag_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.owl.card.common.protobuf.cs.UserLoginS2C prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UserLoginS2C}
   *
   * <pre>
   * msgType = 11
   * 服务器 -&gt; 客户端
   * 客户端请求登陆返回
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UserLoginS2C)
      com.owl.card.common.protobuf.cs.UserLoginS2COrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_UserLoginS2C_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_UserLoginS2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.owl.card.common.protobuf.cs.UserLoginS2C.class, com.owl.card.common.protobuf.cs.UserLoginS2C.Builder.class);
    }

    // Construct using com.owl.card.common.protobuf.cs.UserLoginS2C.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      flag_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_UserLoginS2C_descriptor;
    }

    public com.owl.card.common.protobuf.cs.UserLoginS2C getDefaultInstanceForType() {
      return com.owl.card.common.protobuf.cs.UserLoginS2C.getDefaultInstance();
    }

    public com.owl.card.common.protobuf.cs.UserLoginS2C build() {
      com.owl.card.common.protobuf.cs.UserLoginS2C result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.owl.card.common.protobuf.cs.UserLoginS2C buildPartial() {
      com.owl.card.common.protobuf.cs.UserLoginS2C result = new com.owl.card.common.protobuf.cs.UserLoginS2C(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.flag_ = flag_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.owl.card.common.protobuf.cs.UserLoginS2C) {
        return mergeFrom((com.owl.card.common.protobuf.cs.UserLoginS2C)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.owl.card.common.protobuf.cs.UserLoginS2C other) {
      if (other == com.owl.card.common.protobuf.cs.UserLoginS2C.getDefaultInstance()) return this;
      if (other.hasFlag()) {
        setFlag(other.getFlag());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasFlag()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.owl.card.common.protobuf.cs.UserLoginS2C parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.owl.card.common.protobuf.cs.UserLoginS2C) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int flag_ ;
    /**
     * <code>required int32 flag = 1;</code>
     *
     * <pre>
     *0:验证错误 1:登录成功
     * </pre>
     */
    public boolean hasFlag() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 flag = 1;</code>
     *
     * <pre>
     *0:验证错误 1:登录成功
     * </pre>
     */
    public int getFlag() {
      return flag_;
    }
    /**
     * <code>required int32 flag = 1;</code>
     *
     * <pre>
     *0:验证错误 1:登录成功
     * </pre>
     */
    public Builder setFlag(int value) {
      bitField0_ |= 0x00000001;
      flag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 flag = 1;</code>
     *
     * <pre>
     *0:验证错误 1:登录成功
     * </pre>
     */
    public Builder clearFlag() {
      bitField0_ = (bitField0_ & ~0x00000001);
      flag_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:UserLoginS2C)
  }

  static {
    defaultInstance = new UserLoginS2C(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:UserLoginS2C)
}

