// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_msg.proto

package com.owl.card.common.protobuf.cs;

public interface UserLoginS2COrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserLoginS2C)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 flag = 1;</code>
   *
   * <pre>
   *0:验证错误 1:登录成功
   * </pre>
   */
  boolean hasFlag();
  /**
   * <code>required int32 flag = 1;</code>
   *
   * <pre>
   *0:验证错误 1:登录成功
   * </pre>
   */
  int getFlag();
}
