// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_msg.proto

package com.owl.card.common.protobuf.cs;

public interface UserLoginC2SOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required int32 accid = 1;
  /**
   * <code>required int32 accid = 1;</code>
   *
   * <pre>
   * 平台用户ID
   * </pre>
   */
  boolean hasAccid();
  /**
   * <code>required int32 accid = 1;</code>
   *
   * <pre>
   * 平台用户ID
   * </pre>
   */
  int getAccid();

  // required int32 tstamp = 2;
  /**
   * <code>required int32 tstamp = 2;</code>
   *
   * <pre>
   * 时间戳
   * </pre>
   */
  boolean hasTstamp();
  /**
   * <code>required int32 tstamp = 2;</code>
   *
   * <pre>
   * 时间戳
   * </pre>
   */
  int getTstamp();

  // required string ticket = 3;
  /**
   * <code>required string ticket = 3;</code>
   *
   * <pre>
   * 验证码
   * </pre>
   */
  boolean hasTicket();
  /**
   * <code>required string ticket = 3;</code>
   *
   * <pre>
   * 验证码
   * </pre>
   */
  java.lang.String getTicket();
  /**
   * <code>required string ticket = 3;</code>
   *
   * <pre>
   * 验证码
   * </pre>
   */
  com.google.protobuf.ByteString
      getTicketBytes();
}
