// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_msg.proto

package com.owl.card.common.protobuf.cs;

/**
 * Protobuf type {@code UserLoginC2S}
 *
 * <pre>
 * msgType = 10
 * 客户端 -&gt; 服务器
 * 客户端请求登陆
 * </pre>
 */
public final class UserLoginC2S extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:UserLoginC2S)
    UserLoginC2SOrBuilder {
  // Use UserLoginC2S.newBuilder() to construct.
  private UserLoginC2S(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private UserLoginC2S(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final UserLoginC2S defaultInstance;
  public static UserLoginC2S getDefaultInstance() {
    return defaultInstance;
  }

  public UserLoginC2S getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private UserLoginC2S(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            accid_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            tstamp_ = input.readInt32();
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            ticket_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_UserLoginC2S_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_UserLoginC2S_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.owl.card.common.protobuf.cs.UserLoginC2S.class, com.owl.card.common.protobuf.cs.UserLoginC2S.Builder.class);
  }

  public static com.google.protobuf.Parser<UserLoginC2S> PARSER =
      new com.google.protobuf.AbstractParser<UserLoginC2S>() {
    public UserLoginC2S parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserLoginC2S(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<UserLoginC2S> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int ACCID_FIELD_NUMBER = 1;
  private int accid_;
  /**
   * <code>required int32 accid = 1;</code>
   *
   * <pre>
   * 平台用户ID
   * </pre>
   */
  public boolean hasAccid() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int32 accid = 1;</code>
   *
   * <pre>
   * 平台用户ID
   * </pre>
   */
  public int getAccid() {
    return accid_;
  }

  public static final int TSTAMP_FIELD_NUMBER = 2;
  private int tstamp_;
  /**
   * <code>required int32 tstamp = 2;</code>
   *
   * <pre>
   * 时间戳
   * </pre>
   */
  public boolean hasTstamp() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int32 tstamp = 2;</code>
   *
   * <pre>
   * 时间戳
   * </pre>
   */
  public int getTstamp() {
    return tstamp_;
  }

  public static final int TICKET_FIELD_NUMBER = 3;
  private java.lang.Object ticket_;
  /**
   * <code>required string ticket = 3;</code>
   *
   * <pre>
   * 验证码
   * </pre>
   */
  public boolean hasTicket() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required string ticket = 3;</code>
   *
   * <pre>
   * 验证码
   * </pre>
   */
  public java.lang.String getTicket() {
    java.lang.Object ref = ticket_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        ticket_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string ticket = 3;</code>
   *
   * <pre>
   * 验证码
   * </pre>
   */
  public com.google.protobuf.ByteString
      getTicketBytes() {
    java.lang.Object ref = ticket_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ticket_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    accid_ = 0;
    tstamp_ = 0;
    ticket_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasAccid()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasTstamp()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasTicket()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, accid_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, tstamp_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getTicketBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, accid_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, tstamp_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getTicketBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.owl.card.common.protobuf.cs.UserLoginC2S parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginC2S parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginC2S parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginC2S parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginC2S parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginC2S parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginC2S parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginC2S parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginC2S parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginC2S parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.owl.card.common.protobuf.cs.UserLoginC2S prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UserLoginC2S}
   *
   * <pre>
   * msgType = 10
   * 客户端 -&gt; 服务器
   * 客户端请求登陆
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UserLoginC2S)
      com.owl.card.common.protobuf.cs.UserLoginC2SOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_UserLoginC2S_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_UserLoginC2S_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.owl.card.common.protobuf.cs.UserLoginC2S.class, com.owl.card.common.protobuf.cs.UserLoginC2S.Builder.class);
    }

    // Construct using com.owl.card.common.protobuf.cs.UserLoginC2S.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      accid_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      tstamp_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      ticket_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_UserLoginC2S_descriptor;
    }

    public com.owl.card.common.protobuf.cs.UserLoginC2S getDefaultInstanceForType() {
      return com.owl.card.common.protobuf.cs.UserLoginC2S.getDefaultInstance();
    }

    public com.owl.card.common.protobuf.cs.UserLoginC2S build() {
      com.owl.card.common.protobuf.cs.UserLoginC2S result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.owl.card.common.protobuf.cs.UserLoginC2S buildPartial() {
      com.owl.card.common.protobuf.cs.UserLoginC2S result = new com.owl.card.common.protobuf.cs.UserLoginC2S(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.accid_ = accid_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.tstamp_ = tstamp_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.ticket_ = ticket_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.owl.card.common.protobuf.cs.UserLoginC2S) {
        return mergeFrom((com.owl.card.common.protobuf.cs.UserLoginC2S)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.owl.card.common.protobuf.cs.UserLoginC2S other) {
      if (other == com.owl.card.common.protobuf.cs.UserLoginC2S.getDefaultInstance()) return this;
      if (other.hasAccid()) {
        setAccid(other.getAccid());
      }
      if (other.hasTstamp()) {
        setTstamp(other.getTstamp());
      }
      if (other.hasTicket()) {
        bitField0_ |= 0x00000004;
        ticket_ = other.ticket_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasAccid()) {
        
        return false;
      }
      if (!hasTstamp()) {
        
        return false;
      }
      if (!hasTicket()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.owl.card.common.protobuf.cs.UserLoginC2S parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.owl.card.common.protobuf.cs.UserLoginC2S) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int accid_ ;
    /**
     * <code>required int32 accid = 1;</code>
     *
     * <pre>
     * 平台用户ID
     * </pre>
     */
    public boolean hasAccid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 accid = 1;</code>
     *
     * <pre>
     * 平台用户ID
     * </pre>
     */
    public int getAccid() {
      return accid_;
    }
    /**
     * <code>required int32 accid = 1;</code>
     *
     * <pre>
     * 平台用户ID
     * </pre>
     */
    public Builder setAccid(int value) {
      bitField0_ |= 0x00000001;
      accid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 accid = 1;</code>
     *
     * <pre>
     * 平台用户ID
     * </pre>
     */
    public Builder clearAccid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      accid_ = 0;
      onChanged();
      return this;
    }

    private int tstamp_ ;
    /**
     * <code>required int32 tstamp = 2;</code>
     *
     * <pre>
     * 时间戳
     * </pre>
     */
    public boolean hasTstamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 tstamp = 2;</code>
     *
     * <pre>
     * 时间戳
     * </pre>
     */
    public int getTstamp() {
      return tstamp_;
    }
    /**
     * <code>required int32 tstamp = 2;</code>
     *
     * <pre>
     * 时间戳
     * </pre>
     */
    public Builder setTstamp(int value) {
      bitField0_ |= 0x00000002;
      tstamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 tstamp = 2;</code>
     *
     * <pre>
     * 时间戳
     * </pre>
     */
    public Builder clearTstamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      tstamp_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object ticket_ = "";
    /**
     * <code>required string ticket = 3;</code>
     *
     * <pre>
     * 验证码
     * </pre>
     */
    public boolean hasTicket() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string ticket = 3;</code>
     *
     * <pre>
     * 验证码
     * </pre>
     */
    public java.lang.String getTicket() {
      java.lang.Object ref = ticket_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ticket_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string ticket = 3;</code>
     *
     * <pre>
     * 验证码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTicketBytes() {
      java.lang.Object ref = ticket_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ticket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string ticket = 3;</code>
     *
     * <pre>
     * 验证码
     * </pre>
     */
    public Builder setTicket(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      ticket_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string ticket = 3;</code>
     *
     * <pre>
     * 验证码
     * </pre>
     */
    public Builder clearTicket() {
      bitField0_ = (bitField0_ & ~0x00000004);
      ticket_ = getDefaultInstance().getTicket();
      onChanged();
      return this;
    }
    /**
     * <code>required string ticket = 3;</code>
     *
     * <pre>
     * 验证码
     * </pre>
     */
    public Builder setTicketBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      ticket_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:UserLoginC2S)
  }

  static {
    defaultInstance = new UserLoginC2S(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:UserLoginC2S)
}

