// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_msg.proto

package com.owl.card.common.protobuf.cs;

/**
 * Protobuf type {@code UserLoginS2C}
 *
 * <pre>
 * msgType = 11
 * 服务器 -&gt; 客户端
 * 客户端请求登陆返回
 * </pre>
 */
public  final class UserLoginS2C extends
    com.google.protobuf.GeneratedMessage
    implements UserLoginS2COrBuilder {
  // Use UserLoginS2C.newBuilder() to construct.
  private UserLoginS2C(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private UserLoginS2C(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final UserLoginS2C defaultInstance;
  public static UserLoginS2C getDefaultInstance() {
    return defaultInstance;
  }

  public UserLoginS2C getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private UserLoginS2C(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            rt_ = input.readInt32();
            break;
          }
          case 18: {
            com.owl.card.common.protobuf.struct.RoleInfoData.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = roleInfo_.toBuilder();
            }
            roleInfo_ = input.readMessage(com.owl.card.common.protobuf.struct.RoleInfoData.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(roleInfo_);
              roleInfo_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_UserLoginS2C_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_UserLoginS2C_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.owl.card.common.protobuf.cs.UserLoginS2C.class, com.owl.card.common.protobuf.cs.UserLoginS2C.Builder.class);
  }

  public static com.google.protobuf.Parser<UserLoginS2C> PARSER =
      new com.google.protobuf.AbstractParser<UserLoginS2C>() {
    public UserLoginS2C parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserLoginS2C(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<UserLoginS2C> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required int32 rt = 1;
  public static final int RT_FIELD_NUMBER = 1;
  private int rt_;
  /**
   * <code>required int32 rt = 1;</code>
   *
   * <pre>
   * 错误码
   * </pre>
   */
  public boolean hasRt() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int32 rt = 1;</code>
   *
   * <pre>
   * 错误码
   * </pre>
   */
  public int getRt() {
    return rt_;
  }

  // optional .RoleInfoData roleInfo = 2;
  public static final int ROLEINFO_FIELD_NUMBER = 2;
  private com.owl.card.common.protobuf.struct.RoleInfoData roleInfo_;
  /**
   * <code>optional .RoleInfoData roleInfo = 2;</code>
   *
   * <pre>
   * 玩家信息(失败则无)
   * </pre>
   */
  public boolean hasRoleInfo() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .RoleInfoData roleInfo = 2;</code>
   *
   * <pre>
   * 玩家信息(失败则无)
   * </pre>
   */
  public com.owl.card.common.protobuf.struct.RoleInfoData getRoleInfo() {
    return roleInfo_;
  }
  /**
   * <code>optional .RoleInfoData roleInfo = 2;</code>
   *
   * <pre>
   * 玩家信息(失败则无)
   * </pre>
   */
  public com.owl.card.common.protobuf.struct.RoleInfoDataOrBuilder getRoleInfoOrBuilder() {
    return roleInfo_;
  }

  private void initFields() {
    rt_ = 0;
    roleInfo_ = com.owl.card.common.protobuf.struct.RoleInfoData.getDefaultInstance();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasRt()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (hasRoleInfo()) {
      if (!getRoleInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, rt_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, roleInfo_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, rt_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, roleInfo_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.owl.card.common.protobuf.cs.UserLoginS2C parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.owl.card.common.protobuf.cs.UserLoginS2C prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UserLoginS2C}
   *
   * <pre>
   * msgType = 11
   * 服务器 -&gt; 客户端
   * 客户端请求登陆返回
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.owl.card.common.protobuf.cs.UserLoginS2COrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_UserLoginS2C_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_UserLoginS2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.owl.card.common.protobuf.cs.UserLoginS2C.class, com.owl.card.common.protobuf.cs.UserLoginS2C.Builder.class);
    }

    // Construct using com.owl.card.common.protobuf.cs.UserLoginS2C.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getRoleInfoFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      rt_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (roleInfoBuilder_ == null) {
        roleInfo_ = com.owl.card.common.protobuf.struct.RoleInfoData.getDefaultInstance();
      } else {
        roleInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.owl.card.common.protobuf.cs.CardGamePkt.internal_static_UserLoginS2C_descriptor;
    }

    public com.owl.card.common.protobuf.cs.UserLoginS2C getDefaultInstanceForType() {
      return com.owl.card.common.protobuf.cs.UserLoginS2C.getDefaultInstance();
    }

    public com.owl.card.common.protobuf.cs.UserLoginS2C build() {
      com.owl.card.common.protobuf.cs.UserLoginS2C result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.owl.card.common.protobuf.cs.UserLoginS2C buildPartial() {
      com.owl.card.common.protobuf.cs.UserLoginS2C result = new com.owl.card.common.protobuf.cs.UserLoginS2C(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.rt_ = rt_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (roleInfoBuilder_ == null) {
        result.roleInfo_ = roleInfo_;
      } else {
        result.roleInfo_ = roleInfoBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.owl.card.common.protobuf.cs.UserLoginS2C) {
        return mergeFrom((com.owl.card.common.protobuf.cs.UserLoginS2C)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.owl.card.common.protobuf.cs.UserLoginS2C other) {
      if (other == com.owl.card.common.protobuf.cs.UserLoginS2C.getDefaultInstance()) return this;
      if (other.hasRt()) {
        setRt(other.getRt());
      }
      if (other.hasRoleInfo()) {
        mergeRoleInfo(other.getRoleInfo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasRt()) {
        
        return false;
      }
      if (hasRoleInfo()) {
        if (!getRoleInfo().isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.owl.card.common.protobuf.cs.UserLoginS2C parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.owl.card.common.protobuf.cs.UserLoginS2C) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required int32 rt = 1;
    private int rt_ ;
    /**
     * <code>required int32 rt = 1;</code>
     *
     * <pre>
     * 错误码
     * </pre>
     */
    public boolean hasRt() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 rt = 1;</code>
     *
     * <pre>
     * 错误码
     * </pre>
     */
    public int getRt() {
      return rt_;
    }
    /**
     * <code>required int32 rt = 1;</code>
     *
     * <pre>
     * 错误码
     * </pre>
     */
    public Builder setRt(int value) {
      bitField0_ |= 0x00000001;
      rt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 rt = 1;</code>
     *
     * <pre>
     * 错误码
     * </pre>
     */
    public Builder clearRt() {
      bitField0_ = (bitField0_ & ~0x00000001);
      rt_ = 0;
      onChanged();
      return this;
    }

    // optional .RoleInfoData roleInfo = 2;
    private com.owl.card.common.protobuf.struct.RoleInfoData roleInfo_ = com.owl.card.common.protobuf.struct.RoleInfoData.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.owl.card.common.protobuf.struct.RoleInfoData, com.owl.card.common.protobuf.struct.RoleInfoData.Builder, com.owl.card.common.protobuf.struct.RoleInfoDataOrBuilder> roleInfoBuilder_;
    /**
     * <code>optional .RoleInfoData roleInfo = 2;</code>
     *
     * <pre>
     * 玩家信息(失败则无)
     * </pre>
     */
    public boolean hasRoleInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .RoleInfoData roleInfo = 2;</code>
     *
     * <pre>
     * 玩家信息(失败则无)
     * </pre>
     */
    public com.owl.card.common.protobuf.struct.RoleInfoData getRoleInfo() {
      if (roleInfoBuilder_ == null) {
        return roleInfo_;
      } else {
        return roleInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .RoleInfoData roleInfo = 2;</code>
     *
     * <pre>
     * 玩家信息(失败则无)
     * </pre>
     */
    public Builder setRoleInfo(com.owl.card.common.protobuf.struct.RoleInfoData value) {
      if (roleInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        roleInfo_ = value;
        onChanged();
      } else {
        roleInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .RoleInfoData roleInfo = 2;</code>
     *
     * <pre>
     * 玩家信息(失败则无)
     * </pre>
     */
    public Builder setRoleInfo(
        com.owl.card.common.protobuf.struct.RoleInfoData.Builder builderForValue) {
      if (roleInfoBuilder_ == null) {
        roleInfo_ = builderForValue.build();
        onChanged();
      } else {
        roleInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .RoleInfoData roleInfo = 2;</code>
     *
     * <pre>
     * 玩家信息(失败则无)
     * </pre>
     */
    public Builder mergeRoleInfo(com.owl.card.common.protobuf.struct.RoleInfoData value) {
      if (roleInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            roleInfo_ != com.owl.card.common.protobuf.struct.RoleInfoData.getDefaultInstance()) {
          roleInfo_ =
            com.owl.card.common.protobuf.struct.RoleInfoData.newBuilder(roleInfo_).mergeFrom(value).buildPartial();
        } else {
          roleInfo_ = value;
        }
        onChanged();
      } else {
        roleInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .RoleInfoData roleInfo = 2;</code>
     *
     * <pre>
     * 玩家信息(失败则无)
     * </pre>
     */
    public Builder clearRoleInfo() {
      if (roleInfoBuilder_ == null) {
        roleInfo_ = com.owl.card.common.protobuf.struct.RoleInfoData.getDefaultInstance();
        onChanged();
      } else {
        roleInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .RoleInfoData roleInfo = 2;</code>
     *
     * <pre>
     * 玩家信息(失败则无)
     * </pre>
     */
    public com.owl.card.common.protobuf.struct.RoleInfoData.Builder getRoleInfoBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getRoleInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .RoleInfoData roleInfo = 2;</code>
     *
     * <pre>
     * 玩家信息(失败则无)
     * </pre>
     */
    public com.owl.card.common.protobuf.struct.RoleInfoDataOrBuilder getRoleInfoOrBuilder() {
      if (roleInfoBuilder_ != null) {
        return roleInfoBuilder_.getMessageOrBuilder();
      } else {
        return roleInfo_;
      }
    }
    /**
     * <code>optional .RoleInfoData roleInfo = 2;</code>
     *
     * <pre>
     * 玩家信息(失败则无)
     * </pre>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.owl.card.common.protobuf.struct.RoleInfoData, com.owl.card.common.protobuf.struct.RoleInfoData.Builder, com.owl.card.common.protobuf.struct.RoleInfoDataOrBuilder> 
        getRoleInfoFieldBuilder() {
      if (roleInfoBuilder_ == null) {
        roleInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.owl.card.common.protobuf.struct.RoleInfoData, com.owl.card.common.protobuf.struct.RoleInfoData.Builder, com.owl.card.common.protobuf.struct.RoleInfoDataOrBuilder>(
                roleInfo_,
                getParentForChildren(),
                isClean());
        roleInfo_ = null;
      }
      return roleInfoBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:UserLoginS2C)
  }

  static {
    defaultInstance = new UserLoginS2C(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:UserLoginS2C)
}

