// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_msg.proto

package com.owl.card.common.protobuf.cs;

public interface UserLoginS2COrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required int32 rt = 1;
  /**
   * <code>required int32 rt = 1;</code>
   *
   * <pre>
   * 错误码
   * </pre>
   */
  boolean hasRt();
  /**
   * <code>required int32 rt = 1;</code>
   *
   * <pre>
   * 错误码
   * </pre>
   */
  int getRt();

  // optional .RoleInfoData roleInfo = 2;
  /**
   * <code>optional .RoleInfoData roleInfo = 2;</code>
   *
   * <pre>
   * 玩家信息(失败则无)
   * </pre>
   */
  boolean hasRoleInfo();
  /**
   * <code>optional .RoleInfoData roleInfo = 2;</code>
   *
   * <pre>
   * 玩家信息(失败则无)
   * </pre>
   */
  com.owl.card.common.protobuf.struct.RoleInfoData getRoleInfo();
  /**
   * <code>optional .RoleInfoData roleInfo = 2;</code>
   *
   * <pre>
   * 玩家信息(失败则无)
   * </pre>
   */
  com.owl.card.common.protobuf.struct.RoleInfoDataOrBuilder getRoleInfoOrBuilder();
}
