// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_struct.proto

package com.owl.card.common.protobuf.struct;

public final class CardStructPkt {
  private CardStructPkt() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_RoleInfoData_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RoleInfoData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020msg_struct.proto\"J\n\014RoleInfoData\022\014\n\004na" +
      "me\030\001 \001(\t\022\014\n\004gold\030\002 \002(\005\022\017\n\007diamond\030\003 \002(\005\022" +
      "\r\n\005point\030\004 \002(\005B6\n#com.owl.card.common.pr" +
      "otobuf.structB\rCardStructPktP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RoleInfoData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RoleInfoData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RoleInfoData_descriptor,
              new java.lang.String[] { "Name", "Gold", "Diamond", "Point", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
