// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_struct.proto

package com.owl.card.common.protobuf.struct;

public interface CardInfoOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required int32 protoId = 1;
  /**
   * <code>required int32 protoId = 1;</code>
   *
   * <pre>
   * 卡牌编号
   * </pre>
   */
  boolean hasProtoId();
  /**
   * <code>required int32 protoId = 1;</code>
   *
   * <pre>
   * 卡牌编号
   * </pre>
   */
  int getProtoId();

  // required int32 num = 2;
  /**
   * <code>required int32 num = 2;</code>
   *
   * <pre>
   * 数量
   * </pre>
   */
  boolean hasNum();
  /**
   * <code>required int32 num = 2;</code>
   *
   * <pre>
   * 数量
   * </pre>
   */
  int getNum();
}
