// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_struct.proto

package com.owl.card.common.protobuf.struct;

public interface CardGroupInfoOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required int64 groupId = 1;
  /**
   * <code>required int64 groupId = 1;</code>
   *
   * <pre>
   * 组号
   * </pre>
   */
  boolean hasGroupId();
  /**
   * <code>required int64 groupId = 1;</code>
   *
   * <pre>
   * 组号
   * </pre>
   */
  long getGroupId();

  // required string groupName = 2;
  /**
   * <code>required string groupName = 2;</code>
   *
   * <pre>
   * 组名
   * </pre>
   */
  boolean hasGroupName();
  /**
   * <code>required string groupName = 2;</code>
   *
   * <pre>
   * 组名
   * </pre>
   */
  java.lang.String getGroupName();
  /**
   * <code>required string groupName = 2;</code>
   *
   * <pre>
   * 组名
   * </pre>
   */
  com.google.protobuf.ByteString
      getGroupNameBytes();

  // required int32 heroCareer = 3;
  /**
   * <code>required int32 heroCareer = 3;</code>
   *
   * <pre>
   * 英雄
   * </pre>
   */
  boolean hasHeroCareer();
  /**
   * <code>required int32 heroCareer = 3;</code>
   *
   * <pre>
   * 英雄
   * </pre>
   */
  int getHeroCareer();

  // repeated int32 cardProtoId = 4;
  /**
   * <code>repeated int32 cardProtoId = 4;</code>
   *
   * <pre>
   * 卡牌编号
   * </pre>
   */
  java.util.List<java.lang.Integer> getCardProtoIdList();
  /**
   * <code>repeated int32 cardProtoId = 4;</code>
   *
   * <pre>
   * 卡牌编号
   * </pre>
   */
  int getCardProtoIdCount();
  /**
   * <code>repeated int32 cardProtoId = 4;</code>
   *
   * <pre>
   * 卡牌编号
   * </pre>
   */
  int getCardProtoId(int index);
}
