// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_struct.proto

package com.owl.card.common.protobuf.struct;

public interface RoleInfoDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoleInfoData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * 姓名(可能无)
   * </pre>
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * 姓名(可能无)
   * </pre>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * 姓名(可能无)
   * </pre>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required int32 gold = 2;</code>
   *
   * <pre>
   * 金币
   * </pre>
   */
  boolean hasGold();
  /**
   * <code>required int32 gold = 2;</code>
   *
   * <pre>
   * 金币
   * </pre>
   */
  int getGold();

  /**
   * <code>required int32 diamond = 3;</code>
   *
   * <pre>
   * 钻石
   * </pre>
   */
  boolean hasDiamond();
  /**
   * <code>required int32 diamond = 3;</code>
   *
   * <pre>
   * 钻石
   * </pre>
   */
  int getDiamond();

  /**
   * <code>required int32 point = 4;</code>
   *
   * <pre>
   * 积分(卡牌碎片)
   * </pre>
   */
  boolean hasPoint();
  /**
   * <code>required int32 point = 4;</code>
   *
   * <pre>
   * 积分(卡牌碎片)
   * </pre>
   */
  int getPoint();
}
