// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_struct.proto

package com.owl.card.common.protobuf.struct;

public interface RoleInfoDataOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string name = 1;
  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * 姓名(可能无)
   * </pre>
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * 姓名(可能无)
   * </pre>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * 姓名(可能无)
   * </pre>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  // required int32 gold = 2;
  /**
   * <code>required int32 gold = 2;</code>
   *
   * <pre>
   * 金币
   * </pre>
   */
  boolean hasGold();
  /**
   * <code>required int32 gold = 2;</code>
   *
   * <pre>
   * 金币
   * </pre>
   */
  int getGold();

  // required int32 diamond = 3;
  /**
   * <code>required int32 diamond = 3;</code>
   *
   * <pre>
   * 钻石
   * </pre>
   */
  boolean hasDiamond();
  /**
   * <code>required int32 diamond = 3;</code>
   *
   * <pre>
   * 钻石
   * </pre>
   */
  int getDiamond();

  // required int32 point = 4;
  /**
   * <code>required int32 point = 4;</code>
   *
   * <pre>
   * 积分(卡牌碎片)
   * </pre>
   */
  boolean hasPoint();
  /**
   * <code>required int32 point = 4;</code>
   *
   * <pre>
   * 积分(卡牌碎片)
   * </pre>
   */
  int getPoint();

  // repeated .CardInfo card = 5;
  /**
   * <code>repeated .CardInfo card = 5;</code>
   *
   * <pre>
   * 卡牌信息
   * </pre>
   */
  java.util.List<com.owl.card.common.protobuf.struct.CardInfo> 
      getCardList();
  /**
   * <code>repeated .CardInfo card = 5;</code>
   *
   * <pre>
   * 卡牌信息
   * </pre>
   */
  com.owl.card.common.protobuf.struct.CardInfo getCard(int index);
  /**
   * <code>repeated .CardInfo card = 5;</code>
   *
   * <pre>
   * 卡牌信息
   * </pre>
   */
  int getCardCount();
  /**
   * <code>repeated .CardInfo card = 5;</code>
   *
   * <pre>
   * 卡牌信息
   * </pre>
   */
  java.util.List<? extends com.owl.card.common.protobuf.struct.CardInfoOrBuilder> 
      getCardOrBuilderList();
  /**
   * <code>repeated .CardInfo card = 5;</code>
   *
   * <pre>
   * 卡牌信息
   * </pre>
   */
  com.owl.card.common.protobuf.struct.CardInfoOrBuilder getCardOrBuilder(
      int index);

  // repeated .CardGroupInfo group = 6;
  /**
   * <code>repeated .CardGroupInfo group = 6;</code>
   *
   * <pre>
   * 卡组信息
   * </pre>
   */
  java.util.List<com.owl.card.common.protobuf.struct.CardGroupInfo> 
      getGroupList();
  /**
   * <code>repeated .CardGroupInfo group = 6;</code>
   *
   * <pre>
   * 卡组信息
   * </pre>
   */
  com.owl.card.common.protobuf.struct.CardGroupInfo getGroup(int index);
  /**
   * <code>repeated .CardGroupInfo group = 6;</code>
   *
   * <pre>
   * 卡组信息
   * </pre>
   */
  int getGroupCount();
  /**
   * <code>repeated .CardGroupInfo group = 6;</code>
   *
   * <pre>
   * 卡组信息
   * </pre>
   */
  java.util.List<? extends com.owl.card.common.protobuf.struct.CardGroupInfoOrBuilder> 
      getGroupOrBuilderList();
  /**
   * <code>repeated .CardGroupInfo group = 6;</code>
   *
   * <pre>
   * 卡组信息
   * </pre>
   */
  com.owl.card.common.protobuf.struct.CardGroupInfoOrBuilder getGroupOrBuilder(
      int index);
}
