// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_struct.proto

package com.owl.card.common.protobuf.struct;

/**
 * Protobuf type {@code RoleInfoData}
 *
 * <pre>
 * 玩家信息
 * </pre>
 */
public  final class RoleInfoData extends
    com.google.protobuf.GeneratedMessage
    implements RoleInfoDataOrBuilder {
  // Use RoleInfoData.newBuilder() to construct.
  private RoleInfoData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private RoleInfoData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final RoleInfoData defaultInstance;
  public static RoleInfoData getDefaultInstance() {
    return defaultInstance;
  }

  public RoleInfoData getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private RoleInfoData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            name_ = input.readBytes();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            gold_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            diamond_ = input.readInt32();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            point_ = input.readInt32();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              card_ = new java.util.ArrayList<com.owl.card.common.protobuf.struct.CardInfo>();
              mutable_bitField0_ |= 0x00000010;
            }
            card_.add(input.readMessage(com.owl.card.common.protobuf.struct.CardInfo.PARSER, extensionRegistry));
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              group_ = new java.util.ArrayList<com.owl.card.common.protobuf.struct.CardGroupInfo>();
              mutable_bitField0_ |= 0x00000020;
            }
            group_.add(input.readMessage(com.owl.card.common.protobuf.struct.CardGroupInfo.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        card_ = java.util.Collections.unmodifiableList(card_);
      }
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        group_ = java.util.Collections.unmodifiableList(group_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.owl.card.common.protobuf.struct.CardStructPkt.internal_static_RoleInfoData_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.owl.card.common.protobuf.struct.CardStructPkt.internal_static_RoleInfoData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.owl.card.common.protobuf.struct.RoleInfoData.class, com.owl.card.common.protobuf.struct.RoleInfoData.Builder.class);
  }

  public static com.google.protobuf.Parser<RoleInfoData> PARSER =
      new com.google.protobuf.AbstractParser<RoleInfoData>() {
    public RoleInfoData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RoleInfoData(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<RoleInfoData> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional string name = 1;
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.Object name_;
  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * 姓名(可能无)
   * </pre>
   */
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * 姓名(可能无)
   * </pre>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * 姓名(可能无)
   * </pre>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required int32 gold = 2;
  public static final int GOLD_FIELD_NUMBER = 2;
  private int gold_;
  /**
   * <code>required int32 gold = 2;</code>
   *
   * <pre>
   * 金币
   * </pre>
   */
  public boolean hasGold() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int32 gold = 2;</code>
   *
   * <pre>
   * 金币
   * </pre>
   */
  public int getGold() {
    return gold_;
  }

  // required int32 diamond = 3;
  public static final int DIAMOND_FIELD_NUMBER = 3;
  private int diamond_;
  /**
   * <code>required int32 diamond = 3;</code>
   *
   * <pre>
   * 钻石
   * </pre>
   */
  public boolean hasDiamond() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required int32 diamond = 3;</code>
   *
   * <pre>
   * 钻石
   * </pre>
   */
  public int getDiamond() {
    return diamond_;
  }

  // required int32 point = 4;
  public static final int POINT_FIELD_NUMBER = 4;
  private int point_;
  /**
   * <code>required int32 point = 4;</code>
   *
   * <pre>
   * 积分(卡牌碎片)
   * </pre>
   */
  public boolean hasPoint() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>required int32 point = 4;</code>
   *
   * <pre>
   * 积分(卡牌碎片)
   * </pre>
   */
  public int getPoint() {
    return point_;
  }

  // repeated .CardInfo card = 5;
  public static final int CARD_FIELD_NUMBER = 5;
  private java.util.List<com.owl.card.common.protobuf.struct.CardInfo> card_;
  /**
   * <code>repeated .CardInfo card = 5;</code>
   *
   * <pre>
   * 卡牌信息
   * </pre>
   */
  public java.util.List<com.owl.card.common.protobuf.struct.CardInfo> getCardList() {
    return card_;
  }
  /**
   * <code>repeated .CardInfo card = 5;</code>
   *
   * <pre>
   * 卡牌信息
   * </pre>
   */
  public java.util.List<? extends com.owl.card.common.protobuf.struct.CardInfoOrBuilder> 
      getCardOrBuilderList() {
    return card_;
  }
  /**
   * <code>repeated .CardInfo card = 5;</code>
   *
   * <pre>
   * 卡牌信息
   * </pre>
   */
  public int getCardCount() {
    return card_.size();
  }
  /**
   * <code>repeated .CardInfo card = 5;</code>
   *
   * <pre>
   * 卡牌信息
   * </pre>
   */
  public com.owl.card.common.protobuf.struct.CardInfo getCard(int index) {
    return card_.get(index);
  }
  /**
   * <code>repeated .CardInfo card = 5;</code>
   *
   * <pre>
   * 卡牌信息
   * </pre>
   */
  public com.owl.card.common.protobuf.struct.CardInfoOrBuilder getCardOrBuilder(
      int index) {
    return card_.get(index);
  }

  // repeated .CardGroupInfo group = 6;
  public static final int GROUP_FIELD_NUMBER = 6;
  private java.util.List<com.owl.card.common.protobuf.struct.CardGroupInfo> group_;
  /**
   * <code>repeated .CardGroupInfo group = 6;</code>
   *
   * <pre>
   * 卡组信息
   * </pre>
   */
  public java.util.List<com.owl.card.common.protobuf.struct.CardGroupInfo> getGroupList() {
    return group_;
  }
  /**
   * <code>repeated .CardGroupInfo group = 6;</code>
   *
   * <pre>
   * 卡组信息
   * </pre>
   */
  public java.util.List<? extends com.owl.card.common.protobuf.struct.CardGroupInfoOrBuilder> 
      getGroupOrBuilderList() {
    return group_;
  }
  /**
   * <code>repeated .CardGroupInfo group = 6;</code>
   *
   * <pre>
   * 卡组信息
   * </pre>
   */
  public int getGroupCount() {
    return group_.size();
  }
  /**
   * <code>repeated .CardGroupInfo group = 6;</code>
   *
   * <pre>
   * 卡组信息
   * </pre>
   */
  public com.owl.card.common.protobuf.struct.CardGroupInfo getGroup(int index) {
    return group_.get(index);
  }
  /**
   * <code>repeated .CardGroupInfo group = 6;</code>
   *
   * <pre>
   * 卡组信息
   * </pre>
   */
  public com.owl.card.common.protobuf.struct.CardGroupInfoOrBuilder getGroupOrBuilder(
      int index) {
    return group_.get(index);
  }

  private void initFields() {
    name_ = "";
    gold_ = 0;
    diamond_ = 0;
    point_ = 0;
    card_ = java.util.Collections.emptyList();
    group_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasGold()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDiamond()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasPoint()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getCardCount(); i++) {
      if (!getCard(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    for (int i = 0; i < getGroupCount(); i++) {
      if (!getGroup(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getNameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, gold_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, diamond_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt32(4, point_);
    }
    for (int i = 0; i < card_.size(); i++) {
      output.writeMessage(5, card_.get(i));
    }
    for (int i = 0; i < group_.size(); i++) {
      output.writeMessage(6, group_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getNameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, gold_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, diamond_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, point_);
    }
    for (int i = 0; i < card_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, card_.get(i));
    }
    for (int i = 0; i < group_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, group_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.owl.card.common.protobuf.struct.RoleInfoData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.owl.card.common.protobuf.struct.RoleInfoData prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RoleInfoData}
   *
   * <pre>
   * 玩家信息
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.owl.card.common.protobuf.struct.RoleInfoDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.owl.card.common.protobuf.struct.CardStructPkt.internal_static_RoleInfoData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.owl.card.common.protobuf.struct.CardStructPkt.internal_static_RoleInfoData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.owl.card.common.protobuf.struct.RoleInfoData.class, com.owl.card.common.protobuf.struct.RoleInfoData.Builder.class);
    }

    // Construct using com.owl.card.common.protobuf.struct.RoleInfoData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getCardFieldBuilder();
        getGroupFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      gold_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      diamond_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      point_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      if (cardBuilder_ == null) {
        card_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        cardBuilder_.clear();
      }
      if (groupBuilder_ == null) {
        group_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        groupBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.owl.card.common.protobuf.struct.CardStructPkt.internal_static_RoleInfoData_descriptor;
    }

    public com.owl.card.common.protobuf.struct.RoleInfoData getDefaultInstanceForType() {
      return com.owl.card.common.protobuf.struct.RoleInfoData.getDefaultInstance();
    }

    public com.owl.card.common.protobuf.struct.RoleInfoData build() {
      com.owl.card.common.protobuf.struct.RoleInfoData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.owl.card.common.protobuf.struct.RoleInfoData buildPartial() {
      com.owl.card.common.protobuf.struct.RoleInfoData result = new com.owl.card.common.protobuf.struct.RoleInfoData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.gold_ = gold_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.diamond_ = diamond_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.point_ = point_;
      if (cardBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          card_ = java.util.Collections.unmodifiableList(card_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.card_ = card_;
      } else {
        result.card_ = cardBuilder_.build();
      }
      if (groupBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          group_ = java.util.Collections.unmodifiableList(group_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.group_ = group_;
      } else {
        result.group_ = groupBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.owl.card.common.protobuf.struct.RoleInfoData) {
        return mergeFrom((com.owl.card.common.protobuf.struct.RoleInfoData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.owl.card.common.protobuf.struct.RoleInfoData other) {
      if (other == com.owl.card.common.protobuf.struct.RoleInfoData.getDefaultInstance()) return this;
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasGold()) {
        setGold(other.getGold());
      }
      if (other.hasDiamond()) {
        setDiamond(other.getDiamond());
      }
      if (other.hasPoint()) {
        setPoint(other.getPoint());
      }
      if (cardBuilder_ == null) {
        if (!other.card_.isEmpty()) {
          if (card_.isEmpty()) {
            card_ = other.card_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureCardIsMutable();
            card_.addAll(other.card_);
          }
          onChanged();
        }
      } else {
        if (!other.card_.isEmpty()) {
          if (cardBuilder_.isEmpty()) {
            cardBuilder_.dispose();
            cardBuilder_ = null;
            card_ = other.card_;
            bitField0_ = (bitField0_ & ~0x00000010);
            cardBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getCardFieldBuilder() : null;
          } else {
            cardBuilder_.addAllMessages(other.card_);
          }
        }
      }
      if (groupBuilder_ == null) {
        if (!other.group_.isEmpty()) {
          if (group_.isEmpty()) {
            group_ = other.group_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureGroupIsMutable();
            group_.addAll(other.group_);
          }
          onChanged();
        }
      } else {
        if (!other.group_.isEmpty()) {
          if (groupBuilder_.isEmpty()) {
            groupBuilder_.dispose();
            groupBuilder_ = null;
            group_ = other.group_;
            bitField0_ = (bitField0_ & ~0x00000020);
            groupBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getGroupFieldBuilder() : null;
          } else {
            groupBuilder_.addAllMessages(other.group_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasGold()) {
        
        return false;
      }
      if (!hasDiamond()) {
        
        return false;
      }
      if (!hasPoint()) {
        
        return false;
      }
      for (int i = 0; i < getCardCount(); i++) {
        if (!getCard(i).isInitialized()) {
          
          return false;
        }
      }
      for (int i = 0; i < getGroupCount(); i++) {
        if (!getGroup(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.owl.card.common.protobuf.struct.RoleInfoData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.owl.card.common.protobuf.struct.RoleInfoData) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional string name = 1;
    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * 姓名(可能无)
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * 姓名(可能无)
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * 姓名(可能无)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * 姓名(可能无)
     * </pre>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * 姓名(可能无)
     * </pre>
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * 姓名(可能无)
     * </pre>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    // required int32 gold = 2;
    private int gold_ ;
    /**
     * <code>required int32 gold = 2;</code>
     *
     * <pre>
     * 金币
     * </pre>
     */
    public boolean hasGold() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 gold = 2;</code>
     *
     * <pre>
     * 金币
     * </pre>
     */
    public int getGold() {
      return gold_;
    }
    /**
     * <code>required int32 gold = 2;</code>
     *
     * <pre>
     * 金币
     * </pre>
     */
    public Builder setGold(int value) {
      bitField0_ |= 0x00000002;
      gold_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 gold = 2;</code>
     *
     * <pre>
     * 金币
     * </pre>
     */
    public Builder clearGold() {
      bitField0_ = (bitField0_ & ~0x00000002);
      gold_ = 0;
      onChanged();
      return this;
    }

    // required int32 diamond = 3;
    private int diamond_ ;
    /**
     * <code>required int32 diamond = 3;</code>
     *
     * <pre>
     * 钻石
     * </pre>
     */
    public boolean hasDiamond() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 diamond = 3;</code>
     *
     * <pre>
     * 钻石
     * </pre>
     */
    public int getDiamond() {
      return diamond_;
    }
    /**
     * <code>required int32 diamond = 3;</code>
     *
     * <pre>
     * 钻石
     * </pre>
     */
    public Builder setDiamond(int value) {
      bitField0_ |= 0x00000004;
      diamond_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 diamond = 3;</code>
     *
     * <pre>
     * 钻石
     * </pre>
     */
    public Builder clearDiamond() {
      bitField0_ = (bitField0_ & ~0x00000004);
      diamond_ = 0;
      onChanged();
      return this;
    }

    // required int32 point = 4;
    private int point_ ;
    /**
     * <code>required int32 point = 4;</code>
     *
     * <pre>
     * 积分(卡牌碎片)
     * </pre>
     */
    public boolean hasPoint() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 point = 4;</code>
     *
     * <pre>
     * 积分(卡牌碎片)
     * </pre>
     */
    public int getPoint() {
      return point_;
    }
    /**
     * <code>required int32 point = 4;</code>
     *
     * <pre>
     * 积分(卡牌碎片)
     * </pre>
     */
    public Builder setPoint(int value) {
      bitField0_ |= 0x00000008;
      point_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 point = 4;</code>
     *
     * <pre>
     * 积分(卡牌碎片)
     * </pre>
     */
    public Builder clearPoint() {
      bitField0_ = (bitField0_ & ~0x00000008);
      point_ = 0;
      onChanged();
      return this;
    }

    // repeated .CardInfo card = 5;
    private java.util.List<com.owl.card.common.protobuf.struct.CardInfo> card_ =
      java.util.Collections.emptyList();
    private void ensureCardIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        card_ = new java.util.ArrayList<com.owl.card.common.protobuf.struct.CardInfo>(card_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.owl.card.common.protobuf.struct.CardInfo, com.owl.card.common.protobuf.struct.CardInfo.Builder, com.owl.card.common.protobuf.struct.CardInfoOrBuilder> cardBuilder_;

    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public java.util.List<com.owl.card.common.protobuf.struct.CardInfo> getCardList() {
      if (cardBuilder_ == null) {
        return java.util.Collections.unmodifiableList(card_);
      } else {
        return cardBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public int getCardCount() {
      if (cardBuilder_ == null) {
        return card_.size();
      } else {
        return cardBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public com.owl.card.common.protobuf.struct.CardInfo getCard(int index) {
      if (cardBuilder_ == null) {
        return card_.get(index);
      } else {
        return cardBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public Builder setCard(
        int index, com.owl.card.common.protobuf.struct.CardInfo value) {
      if (cardBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCardIsMutable();
        card_.set(index, value);
        onChanged();
      } else {
        cardBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public Builder setCard(
        int index, com.owl.card.common.protobuf.struct.CardInfo.Builder builderForValue) {
      if (cardBuilder_ == null) {
        ensureCardIsMutable();
        card_.set(index, builderForValue.build());
        onChanged();
      } else {
        cardBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public Builder addCard(com.owl.card.common.protobuf.struct.CardInfo value) {
      if (cardBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCardIsMutable();
        card_.add(value);
        onChanged();
      } else {
        cardBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public Builder addCard(
        int index, com.owl.card.common.protobuf.struct.CardInfo value) {
      if (cardBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCardIsMutable();
        card_.add(index, value);
        onChanged();
      } else {
        cardBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public Builder addCard(
        com.owl.card.common.protobuf.struct.CardInfo.Builder builderForValue) {
      if (cardBuilder_ == null) {
        ensureCardIsMutable();
        card_.add(builderForValue.build());
        onChanged();
      } else {
        cardBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public Builder addCard(
        int index, com.owl.card.common.protobuf.struct.CardInfo.Builder builderForValue) {
      if (cardBuilder_ == null) {
        ensureCardIsMutable();
        card_.add(index, builderForValue.build());
        onChanged();
      } else {
        cardBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public Builder addAllCard(
        java.lang.Iterable<? extends com.owl.card.common.protobuf.struct.CardInfo> values) {
      if (cardBuilder_ == null) {
        ensureCardIsMutable();
        super.addAll(values, card_);
        onChanged();
      } else {
        cardBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public Builder clearCard() {
      if (cardBuilder_ == null) {
        card_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        cardBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public Builder removeCard(int index) {
      if (cardBuilder_ == null) {
        ensureCardIsMutable();
        card_.remove(index);
        onChanged();
      } else {
        cardBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public com.owl.card.common.protobuf.struct.CardInfo.Builder getCardBuilder(
        int index) {
      return getCardFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public com.owl.card.common.protobuf.struct.CardInfoOrBuilder getCardOrBuilder(
        int index) {
      if (cardBuilder_ == null) {
        return card_.get(index);  } else {
        return cardBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public java.util.List<? extends com.owl.card.common.protobuf.struct.CardInfoOrBuilder> 
         getCardOrBuilderList() {
      if (cardBuilder_ != null) {
        return cardBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(card_);
      }
    }
    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public com.owl.card.common.protobuf.struct.CardInfo.Builder addCardBuilder() {
      return getCardFieldBuilder().addBuilder(
          com.owl.card.common.protobuf.struct.CardInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public com.owl.card.common.protobuf.struct.CardInfo.Builder addCardBuilder(
        int index) {
      return getCardFieldBuilder().addBuilder(
          index, com.owl.card.common.protobuf.struct.CardInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .CardInfo card = 5;</code>
     *
     * <pre>
     * 卡牌信息
     * </pre>
     */
    public java.util.List<com.owl.card.common.protobuf.struct.CardInfo.Builder> 
         getCardBuilderList() {
      return getCardFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.owl.card.common.protobuf.struct.CardInfo, com.owl.card.common.protobuf.struct.CardInfo.Builder, com.owl.card.common.protobuf.struct.CardInfoOrBuilder> 
        getCardFieldBuilder() {
      if (cardBuilder_ == null) {
        cardBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.owl.card.common.protobuf.struct.CardInfo, com.owl.card.common.protobuf.struct.CardInfo.Builder, com.owl.card.common.protobuf.struct.CardInfoOrBuilder>(
                card_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        card_ = null;
      }
      return cardBuilder_;
    }

    // repeated .CardGroupInfo group = 6;
    private java.util.List<com.owl.card.common.protobuf.struct.CardGroupInfo> group_ =
      java.util.Collections.emptyList();
    private void ensureGroupIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        group_ = new java.util.ArrayList<com.owl.card.common.protobuf.struct.CardGroupInfo>(group_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.owl.card.common.protobuf.struct.CardGroupInfo, com.owl.card.common.protobuf.struct.CardGroupInfo.Builder, com.owl.card.common.protobuf.struct.CardGroupInfoOrBuilder> groupBuilder_;

    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public java.util.List<com.owl.card.common.protobuf.struct.CardGroupInfo> getGroupList() {
      if (groupBuilder_ == null) {
        return java.util.Collections.unmodifiableList(group_);
      } else {
        return groupBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public int getGroupCount() {
      if (groupBuilder_ == null) {
        return group_.size();
      } else {
        return groupBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public com.owl.card.common.protobuf.struct.CardGroupInfo getGroup(int index) {
      if (groupBuilder_ == null) {
        return group_.get(index);
      } else {
        return groupBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public Builder setGroup(
        int index, com.owl.card.common.protobuf.struct.CardGroupInfo value) {
      if (groupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupIsMutable();
        group_.set(index, value);
        onChanged();
      } else {
        groupBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public Builder setGroup(
        int index, com.owl.card.common.protobuf.struct.CardGroupInfo.Builder builderForValue) {
      if (groupBuilder_ == null) {
        ensureGroupIsMutable();
        group_.set(index, builderForValue.build());
        onChanged();
      } else {
        groupBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public Builder addGroup(com.owl.card.common.protobuf.struct.CardGroupInfo value) {
      if (groupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupIsMutable();
        group_.add(value);
        onChanged();
      } else {
        groupBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public Builder addGroup(
        int index, com.owl.card.common.protobuf.struct.CardGroupInfo value) {
      if (groupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupIsMutable();
        group_.add(index, value);
        onChanged();
      } else {
        groupBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public Builder addGroup(
        com.owl.card.common.protobuf.struct.CardGroupInfo.Builder builderForValue) {
      if (groupBuilder_ == null) {
        ensureGroupIsMutable();
        group_.add(builderForValue.build());
        onChanged();
      } else {
        groupBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public Builder addGroup(
        int index, com.owl.card.common.protobuf.struct.CardGroupInfo.Builder builderForValue) {
      if (groupBuilder_ == null) {
        ensureGroupIsMutable();
        group_.add(index, builderForValue.build());
        onChanged();
      } else {
        groupBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public Builder addAllGroup(
        java.lang.Iterable<? extends com.owl.card.common.protobuf.struct.CardGroupInfo> values) {
      if (groupBuilder_ == null) {
        ensureGroupIsMutable();
        super.addAll(values, group_);
        onChanged();
      } else {
        groupBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public Builder clearGroup() {
      if (groupBuilder_ == null) {
        group_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        groupBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public Builder removeGroup(int index) {
      if (groupBuilder_ == null) {
        ensureGroupIsMutable();
        group_.remove(index);
        onChanged();
      } else {
        groupBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public com.owl.card.common.protobuf.struct.CardGroupInfo.Builder getGroupBuilder(
        int index) {
      return getGroupFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public com.owl.card.common.protobuf.struct.CardGroupInfoOrBuilder getGroupOrBuilder(
        int index) {
      if (groupBuilder_ == null) {
        return group_.get(index);  } else {
        return groupBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public java.util.List<? extends com.owl.card.common.protobuf.struct.CardGroupInfoOrBuilder> 
         getGroupOrBuilderList() {
      if (groupBuilder_ != null) {
        return groupBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(group_);
      }
    }
    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public com.owl.card.common.protobuf.struct.CardGroupInfo.Builder addGroupBuilder() {
      return getGroupFieldBuilder().addBuilder(
          com.owl.card.common.protobuf.struct.CardGroupInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public com.owl.card.common.protobuf.struct.CardGroupInfo.Builder addGroupBuilder(
        int index) {
      return getGroupFieldBuilder().addBuilder(
          index, com.owl.card.common.protobuf.struct.CardGroupInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .CardGroupInfo group = 6;</code>
     *
     * <pre>
     * 卡组信息
     * </pre>
     */
    public java.util.List<com.owl.card.common.protobuf.struct.CardGroupInfo.Builder> 
         getGroupBuilderList() {
      return getGroupFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.owl.card.common.protobuf.struct.CardGroupInfo, com.owl.card.common.protobuf.struct.CardGroupInfo.Builder, com.owl.card.common.protobuf.struct.CardGroupInfoOrBuilder> 
        getGroupFieldBuilder() {
      if (groupBuilder_ == null) {
        groupBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.owl.card.common.protobuf.struct.CardGroupInfo, com.owl.card.common.protobuf.struct.CardGroupInfo.Builder, com.owl.card.common.protobuf.struct.CardGroupInfoOrBuilder>(
                group_,
                ((bitField0_ & 0x00000020) == 0x00000020),
                getParentForChildren(),
                isClean());
        group_ = null;
      }
      return groupBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:RoleInfoData)
  }

  static {
    defaultInstance = new RoleInfoData(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:RoleInfoData)
}

