// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_struct.proto

package com.owl.card.common.protobuf.struct;

/**
 * Protobuf type {@code RoleInfoData}
 *
 * <pre>
 * 玩家信息
 * </pre>
 */
public  final class RoleInfoData extends
    com.google.protobuf.GeneratedMessage
    implements RoleInfoDataOrBuilder {
  // Use RoleInfoData.newBuilder() to construct.
  private RoleInfoData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private RoleInfoData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final RoleInfoData defaultInstance;
  public static RoleInfoData getDefaultInstance() {
    return defaultInstance;
  }

  public RoleInfoData getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private RoleInfoData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            name_ = input.readBytes();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            gold_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            diamond_ = input.readInt32();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            point_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.owl.card.common.protobuf.struct.CardStructPkt.internal_static_RoleInfoData_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.owl.card.common.protobuf.struct.CardStructPkt.internal_static_RoleInfoData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.owl.card.common.protobuf.struct.RoleInfoData.class, com.owl.card.common.protobuf.struct.RoleInfoData.Builder.class);
  }

  public static com.google.protobuf.Parser<RoleInfoData> PARSER =
      new com.google.protobuf.AbstractParser<RoleInfoData>() {
    public RoleInfoData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RoleInfoData(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<RoleInfoData> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional string name = 1;
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.Object name_;
  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * 姓名(可能无)
   * </pre>
   */
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * 姓名(可能无)
   * </pre>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * 姓名(可能无)
   * </pre>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required int32 gold = 2;
  public static final int GOLD_FIELD_NUMBER = 2;
  private int gold_;
  /**
   * <code>required int32 gold = 2;</code>
   *
   * <pre>
   * 金币
   * </pre>
   */
  public boolean hasGold() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int32 gold = 2;</code>
   *
   * <pre>
   * 金币
   * </pre>
   */
  public int getGold() {
    return gold_;
  }

  // required int32 diamond = 3;
  public static final int DIAMOND_FIELD_NUMBER = 3;
  private int diamond_;
  /**
   * <code>required int32 diamond = 3;</code>
   *
   * <pre>
   * 钻石
   * </pre>
   */
  public boolean hasDiamond() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required int32 diamond = 3;</code>
   *
   * <pre>
   * 钻石
   * </pre>
   */
  public int getDiamond() {
    return diamond_;
  }

  // required int32 point = 4;
  public static final int POINT_FIELD_NUMBER = 4;
  private int point_;
  /**
   * <code>required int32 point = 4;</code>
   *
   * <pre>
   * 积分(卡牌碎片)
   * </pre>
   */
  public boolean hasPoint() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>required int32 point = 4;</code>
   *
   * <pre>
   * 积分(卡牌碎片)
   * </pre>
   */
  public int getPoint() {
    return point_;
  }

  private void initFields() {
    name_ = "";
    gold_ = 0;
    diamond_ = 0;
    point_ = 0;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasGold()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDiamond()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasPoint()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getNameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, gold_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, diamond_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt32(4, point_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getNameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, gold_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, diamond_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, point_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.owl.card.common.protobuf.struct.RoleInfoData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.owl.card.common.protobuf.struct.RoleInfoData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.owl.card.common.protobuf.struct.RoleInfoData prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RoleInfoData}
   *
   * <pre>
   * 玩家信息
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.owl.card.common.protobuf.struct.RoleInfoDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.owl.card.common.protobuf.struct.CardStructPkt.internal_static_RoleInfoData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.owl.card.common.protobuf.struct.CardStructPkt.internal_static_RoleInfoData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.owl.card.common.protobuf.struct.RoleInfoData.class, com.owl.card.common.protobuf.struct.RoleInfoData.Builder.class);
    }

    // Construct using com.owl.card.common.protobuf.struct.RoleInfoData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      gold_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      diamond_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      point_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.owl.card.common.protobuf.struct.CardStructPkt.internal_static_RoleInfoData_descriptor;
    }

    public com.owl.card.common.protobuf.struct.RoleInfoData getDefaultInstanceForType() {
      return com.owl.card.common.protobuf.struct.RoleInfoData.getDefaultInstance();
    }

    public com.owl.card.common.protobuf.struct.RoleInfoData build() {
      com.owl.card.common.protobuf.struct.RoleInfoData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.owl.card.common.protobuf.struct.RoleInfoData buildPartial() {
      com.owl.card.common.protobuf.struct.RoleInfoData result = new com.owl.card.common.protobuf.struct.RoleInfoData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.gold_ = gold_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.diamond_ = diamond_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.point_ = point_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.owl.card.common.protobuf.struct.RoleInfoData) {
        return mergeFrom((com.owl.card.common.protobuf.struct.RoleInfoData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.owl.card.common.protobuf.struct.RoleInfoData other) {
      if (other == com.owl.card.common.protobuf.struct.RoleInfoData.getDefaultInstance()) return this;
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasGold()) {
        setGold(other.getGold());
      }
      if (other.hasDiamond()) {
        setDiamond(other.getDiamond());
      }
      if (other.hasPoint()) {
        setPoint(other.getPoint());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasGold()) {
        
        return false;
      }
      if (!hasDiamond()) {
        
        return false;
      }
      if (!hasPoint()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.owl.card.common.protobuf.struct.RoleInfoData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.owl.card.common.protobuf.struct.RoleInfoData) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional string name = 1;
    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * 姓名(可能无)
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * 姓名(可能无)
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * 姓名(可能无)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * 姓名(可能无)
     * </pre>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * 姓名(可能无)
     * </pre>
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * 姓名(可能无)
     * </pre>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    // required int32 gold = 2;
    private int gold_ ;
    /**
     * <code>required int32 gold = 2;</code>
     *
     * <pre>
     * 金币
     * </pre>
     */
    public boolean hasGold() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 gold = 2;</code>
     *
     * <pre>
     * 金币
     * </pre>
     */
    public int getGold() {
      return gold_;
    }
    /**
     * <code>required int32 gold = 2;</code>
     *
     * <pre>
     * 金币
     * </pre>
     */
    public Builder setGold(int value) {
      bitField0_ |= 0x00000002;
      gold_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 gold = 2;</code>
     *
     * <pre>
     * 金币
     * </pre>
     */
    public Builder clearGold() {
      bitField0_ = (bitField0_ & ~0x00000002);
      gold_ = 0;
      onChanged();
      return this;
    }

    // required int32 diamond = 3;
    private int diamond_ ;
    /**
     * <code>required int32 diamond = 3;</code>
     *
     * <pre>
     * 钻石
     * </pre>
     */
    public boolean hasDiamond() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 diamond = 3;</code>
     *
     * <pre>
     * 钻石
     * </pre>
     */
    public int getDiamond() {
      return diamond_;
    }
    /**
     * <code>required int32 diamond = 3;</code>
     *
     * <pre>
     * 钻石
     * </pre>
     */
    public Builder setDiamond(int value) {
      bitField0_ |= 0x00000004;
      diamond_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 diamond = 3;</code>
     *
     * <pre>
     * 钻石
     * </pre>
     */
    public Builder clearDiamond() {
      bitField0_ = (bitField0_ & ~0x00000004);
      diamond_ = 0;
      onChanged();
      return this;
    }

    // required int32 point = 4;
    private int point_ ;
    /**
     * <code>required int32 point = 4;</code>
     *
     * <pre>
     * 积分(卡牌碎片)
     * </pre>
     */
    public boolean hasPoint() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 point = 4;</code>
     *
     * <pre>
     * 积分(卡牌碎片)
     * </pre>
     */
    public int getPoint() {
      return point_;
    }
    /**
     * <code>required int32 point = 4;</code>
     *
     * <pre>
     * 积分(卡牌碎片)
     * </pre>
     */
    public Builder setPoint(int value) {
      bitField0_ |= 0x00000008;
      point_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 point = 4;</code>
     *
     * <pre>
     * 积分(卡牌碎片)
     * </pre>
     */
    public Builder clearPoint() {
      bitField0_ = (bitField0_ & ~0x00000008);
      point_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:RoleInfoData)
  }

  static {
    defaultInstance = new RoleInfoData(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:RoleInfoData)
}

